### ISSUE TITLE
Please add option so we can choose which CollisionObj in Prediction

### ISSUE THREAD

**Issue by brian0305** [LeagueSharp/LeagueSharp.Common#116]
I see you have add 4 type Collision Obj but in Prediction you set default it only use Minion, Yasuo Wall ? What about some skill can go through Hero, please add option so we can choose what we want

**Comment by WorstPing** [comment]
Added as a new overload,

public static PredictionOutput GetPrediction(Obj_AI_Base unit,
            float delay,
            float radius,
            float speed,
            CollisionableObjects[] collisionable)
