### ISSUE TITLE
More of a request that an issue. [Orbwalker]

### ISSUE THREAD

**Issue by Battler624** [LeagueSharp/LeagueSharp.Common#150]
I have a request a few requests that i wish to be added
1) that you add a (prioritize farm over harass) for each mode (lasthit,waveclear, and harass) because i want to harass more than farm (unless big minion) if i'm holding harass button and then i wish to waveclear because a big wave is comming and do not wish to harass and so on..

2) Prioritize big minions over small ones as sometimes it will attack the small and leave the big minion to die to our wave of minions

3) something like assassin manager for big minions http://www.joduska.me/forum/topic/751-assassin-manager-for-assassin-characters/
the idea here is when you are holding specific button (lasthit,waveclear, and harass) and a big minion which is about to die is within assassin manager range it will try to prioritize that big minion over the small minion near you

4) Check what is the tower attacking and then do a check if the tower will kill it or not with the hit and if you will kill it before the tower 
For example; lets say there are 2 minions who are both under the tower ofcourse the tower will target one of them and any human player will kill the one the tower is targeting so the tower itself doesn't kill it and therefore lose gold because he will also have time to attack the other minion before the tower kills it but the orbwalker here will attack whichever is closer to you no matter if its killable or not and sometimes making you lose 2 minions instead of losing none

5) LessAttackPriority + LessCastPriority self-explained

I actually had more in mind but i forgot them when writing this.

**Comment by Battler624** [comment]
I remembered one more while playing today, this is already implemented a small bit in vayne hunter i believe, anyway.

6) A check to see if you are kiting enemies and if you are it will attack at your max range otherwise it will run

For example lets assume you are playing Ashe with Q on and Furor upgrade for boots and you are fighting riven if you are using the orbwalker as it is now it will AA>move very little > AA to Maximize damage but it will lead to riven catching up to you because you aren't using your full potential of kiting but instead maximizing on damage so here comes the check^ i mentioned, if you are orbwalking away from the enemy champion it will try to efficiently kite away from the enemy therefore assuring maximum safety and keeping said enemy from gapclosing on you and killing you.

Of course it should either kite to your max range or (in the case of twitch with his temp range extension) a number set by a user *and i believe 500 range* is fine for kiting. 

Another thing that if you are orbwalking away from an enemy and into an enemy that was it will orbwalk as normal unless i have focus selected target on and it will do said check on that specific target.

**Comment by Crisdmc** [comment]
News?

**Comment by h3h3** [comment]
We are working on a reimplementatin for the Common https://github.com/LeagueSharp/LeagueSharp.CommonEx this request will be considered while writing the new Orbwalker.

**Comment by livetorise** [comment]
Would be cool as well if you took into consideration for the next orbwalker the delays based off of attack speed and ping and auto config'd them.

**Comment by Battler624** [comment]
What about the one fluxy was working on? anything? or did it move to CommonEX?

**Comment by ChewyMoon** [comment]
Fluxy said he was going to write a new orbwalker..

**Comment by WorstPing** [comment]
Yeah, I moved the project to him like 2 months ago. It'll just be better for me to build it, but then again :v

**Comment by zezzy** [comment]
Still waiting.

**Comment by Battler624** [comment]
Just read Legacy's post about CommonEx, Does that mean the orbwalker is finished?

**Comment by ChewyMoon** [comment]
Nope, CommonEx is still in rapid-development, and it will more then likely change over the course.

**Comment by drunkenninja** [comment]
I really like all the ideas, I hope they are implemented, especially the kiting range thats something I have championed for a while, but its too complex for me...

**Comment by ChewyMoon** [comment]
Me and @legacy3 are currently designing the new orbwalker, we will take a lot of suggestions into play, as well as making it easy for an assembly to override the orbwalker, and make their own.

**Comment by wfcoder** [comment]
I have a suggestion. Study detuks' DeathWalker code. It's only in alpha but currently better than the common orbwalker in every way (farming/smoothness/under tower farming), but most importantly, NO AA STUTTER!

**Comment by Battler624** [comment]
@ChewyMoon So you guys are being swaped around? first it was Fluxy working on the new orbwalker, then Legacy + L33T(worstping) and now You + Legacy? any reason for that?

**Comment by ChewyMoon** [comment]
Fluxy never was working on the orbwalker afaik

**Comment by Battler624** [comment]
@ChewyMoon He was working on it while i was watching his stream, he added melee prediction to common orbwalker while testing his riven but that was on a week after i opened this request.

This "was" the requests thread https://www.joduska.me/forum/topic/20097-request-orbwalker-features-here/

Anyway chewymoon, is commonex having a new menu of some sort? I really wish for a dropdown menu to change orbwalkers (like xSLx, Deathwalker and Common) instead of a slider.
