### ISSUE TITLE
Orbwalking Force Target

### ISSUE THREAD

**Issue by kekekekek** [LeagueSharp/LeagueSharp.Common#161]
Is there a reason that ForceTarget(Obj_AI_Base) is not the first target to be returned if it's valid?

https://github.com/LeagueSharp/LeagueSharpCommon/blob/master/LeagueSharp.Common/LeagueSharp.Common/Orbwalking.cs#L669-L673

**Comment by h3h3** [comment]
&& InAutoAttackRange(_forcedTarget) <-- only if your ForceTarget is in range

**Comment by kekekekek** [comment]
That literally has nothing to do with my question. Obviously, the forced target should only become the actual target if the forced target is in range.

But why are minions or the target at

https://github.com/LeagueSharp/LeagueSharp.Common/blob/master/LeagueSharp.Common/LeagueSharp.Common/Orbwalking.cs#L633

given a higher priority than the forced target? It kind of defeats the purpose of forcing a target if it's not going to be forced unless ActiveMode == OrbwalkingMode.Combo.
