### ISSUE TITLE
Oops. Prediction Problem?

### ISSUE THREAD

**Issue by BlueSun99** [LeagueSharp/LeagueSharp.Common#205]
![g](https://cloud.githubusercontent.com/assets/3435833/6125565/c4cec1cc-b15a-11e4-83c7-2a9869f9e6a3.png)

yup :smile:
just one picture :smiley:

using xSalice's Religion AIO, but that assembly just uses Q after GetPrediction and calc Hitchance!

maybe no problem on assembly.

calculation error? (20% hitchance on lane fight :sob: )

**Comment by h3h3** [comment]
is this still a problem?

**Comment by BlueSun99** [comment]
@h3h3 well, account that have karthus banned :smile: sorry.
i have no way to verify.
