### ISSUE TITLE
Ignore Overlay while Orbwalking

### ISSUE THREAD

**Issue by DannyX5** [LeagueSharp/LeagueSharp.Common#230]
You know sometimes when your holding orbwalk somewhere and you suddenly hover above one of LoLs UI like character ui and your champion starts glitching for a second.

Is it possible for the orbwalking to ignore the UIs around you?

**Comment by ChewyMoon** [comment]
Uh what..

**Comment by madk** [comment]
When you have your cursor hover the champion image on League's UI and you are pressing a orbwalk key he goes to the direction of that champion, and if you hover your own image (the one on the bottom of the screen on the opposite side of the minimap) you champion starts "spinning".
