### ISSUE TITLE
Found reason why there is AA-canceling problem

### ISSUE THREAD

**Issue by BlueSun99** [LeagueSharp/LeagueSharp.Common#250]
I tested on too many games. Because many korean have AA-canceling problem. (Include me)
We set "Extra Winduptime" to 200. but we still had AA-canceling problem.

Reason is..

Method "CanMove(float extraWindup)" on Orbwalking.cs
I deleted line...
```C#
if (_missileLaunched)
    return true;
```

It has no AA-canceling problem.

But it has big problem after channeling skills like Miss Fortune R and Caitlyn R, Orbwalking stops move before i use another skill.
(Yeah, just stops! It don't attack any object, and don't move to mouse.
But after i use any skill, it works.)

Any good idea to fix this problem?
(I try more to fix this problem on custom game before no Koreans have this problem.)

**Comment by SephLeague** [comment]
Added a missile check disabling option in the menu for you.

**Comment by BlueSun99** [comment]
Not solved my problem.

[AA-canceling problem here.](https://vid.me/tTKt)

**Comment by TheSaltyWaffle** [comment]
I've tried to do the same. I disabled 'Use Missile Check' and I played Miss Fortune. After I use her ultimate the orbwalker still fully works. I cannot reproduce the problem you have.

**Comment by BlueSun99** [comment]
@TheSaltyWaffle I hope my ping would be high. Why my ping is too low! :cry:
