### ISSUE TITLE
Prediction Cone bug

### ISSUE THREAD

**Issue by TheNinow** [LeagueSharp/LeagueSharp.Common#269]
Found out why cass ults are casting backwards when AOE is on and multiple targets are available:
(most assemblies fix it by checking if its casting bullsht and blocking the cast - which is not good because this way it can happen that it's not casting at all)

Basically
https://github.com/LeagueSharp/LeagueSharp.Common/blob/master/Prediction.cs#L670-670
is converting the positions to positions relative to the player, but
https://github.com/LeagueSharp/LeagueSharp.Common/blob/master/Prediction.cs#L709-709
doesn't calculate the real position and is returning the relative position. Replace the line with
CastPosition = (bestCandidate + input.From.To2D()).To3D(),
to make it work properly

**Comment by Esk0r** [comment]
Thanks for reporting it it's fixed now: https://github.com/LeagueSharp/LeagueSharp.Common/commit/757782c76e9d43d191c8cadaf5774447a8880def
