### ISSUE TITLE
Zyra's "Flowers" missing in Orbwalker

### ISSUE THREAD

**Issue by Businezz** [LeagueSharp/LeagueSharp.Common#297]
Hey,

I noticed that the "flowers" of Zyra are not being attacked by the common orbwalker. 

Would you mind to add them or is their a reason why they are not being attacked?

**Comment by HiMutz** [comment]
+ heimer's turrets

**Comment by SephLeague** [comment]
Was added by Kurisu 

https://github.com/LeagueSharp/LeagueSharp.Common/commit/e2be4e013bc83a6c8054f41bdafc273f32979492
