### ISSUE TITLE
FEATURE: Jungle-Clear Orbwalk focuses Small Minions first.

### ISSUE THREAD

**Issue by jayblah** [LeagueSharp/LeagueSharp.Common#305]
Hello Common gurus,

It's been demonstrated mathematically that killing the small minions in a jungle camp results in healthier clears. Could you implement logic that would allow the Lane Clear / Jungle Clear orbwalk to attack small minions in a jungle camp before attacking the main minion? If the concern is enemy invasion, you can implement range logic such as "attack small minions first if no enemy within 1000 yards".

**Comment by SephLeague** [comment]
Added an option in misc for this.
