### ISSUE TITLE
FEATURE: AP and AD specific AA range drawings.

### ISSUE THREAD

**Issue by jayblah** [LeagueSharp/LeagueSharp.Common#306]
Hate to compare this to that "other" script competitor, but it has a wonderful feature that allows you to see only the AA-range of the enemy ADC. With L#, currently, you see all enemies AA range in the Common Orbwalk option, and this can be chaotic. If you could implement sub-options that let you see only the enemy ADC and/or APC AA range, that would be amazing.

If you're curious, the competitor shows all 5 enemy AA ranges as an individual toggle.

**Comment by SephLeague** [comment]
Meh, it will clutter the orbwalker menu more and isn't very important.
