### ISSUE TITLE
Shaco/Mordekaiser/Yorick clone/ghost attacks interfere with orbwalking

### ISSUE THREAD

**Issue by GodLS** [LeagueSharp/LeagueSharp.Common#315]
Trees said it's due to them not being assigned to the correct owner (aka the ghost/clone).

Currently they are assigned to you, and because the attacks contain the word "Attack" in them, an issue appears. (Orbwalker considers them as your own attacks.) 

Thus causing either: 1. You not being able to attack as it's on "cooldown" or 2. Stutters.

I fixed the easier cases being: yorick ghouls, malz voidlings, annie tibbers, elise spiderlings, etc. but cannot find an easy, lightweight solution/workaround to this.

Joduskame may need to fix the core if it is indeed bugged, otherwise somebody can hopefully create a quick fix here.

**Comment by myo** [comment]
This issue is fixed
https://github.com/LeagueSharp/LeagueSharp.Common/blob/master/Orbwalking.cs#L127-#L142
