### ISSUE TITLE
Allied Gangplank Barrels interfere with Laneclear orbwalk.

### ISSUE THREAD

**Issue by jayblah** [LeagueSharp/LeagueSharp.Common#324]
Issue:

If holding Laneclear orbwalk key down while with an allied Gangplank, if the allied Gangplank drops a barrel, you will automatically target the barrel with abilities instead of enemy minions.

**Comment by SephLeague** [comment]
Orbwalker is not responsible for abilities, only for autos.

**Comment by jayblah** [comment]
So in this case, if an assembly's Lane Clear function is using abilities on Gangplank's barrels, does that mean the assembly author himself needs to fix his code?

**Comment by xKurisu** [comment]
Depends but most likely yes the author would have to update it.

**Comment by jayblah** [comment]
Thank you, please feel free to close this ticket. Going to report to the author.
