### ISSUE TITLE
Bug hpbarposition

### ISSUE THREAD

**Issue by salvokt** [LeagueSharp/LeagueSharp.Common#339]
This bug happens only for Baron/Drake and Blue/Red Large monsters
here a screen:http://s22.postimg.org/zfmclp32o/bug.jpg

**Comment by ChewyMoon** [comment]
This issue doesn't belong here. You also need to find offsets (x and y offsets) to make it line up.

**Comment by salvokt** [comment]
the code was working fine before it got broken Text.DrawText(null, dmg.ToString(), (int)enemy.HPBarPosition.X + 108, (int)enemy.HPBarPosition.Y + 41, SharpDX.Color.Black);
using this also for other jungle monster

**Comment by nabbhacker** [comment]
offsets change from patch to patch, you have to re-set them from scratch.

**Comment by salvokt** [comment]
if you see what i wrote on first comment you will see that i said that the offset position of others monsters is still the same it was before got broken.
Also i thinks if this method is called HPBarPosition it have to be related on it not on screen position

**Comment by SephLeague** [comment]
Not a Leaguesharp.Common issue.
