### ISSUE TITLE
TWITCH E 

### ISSUE THREAD

**Issue by mozartsharp** [LeagueSharp/LeagueSharp.Common#345]
CAN YOU FOR THE GOD OF LOVE FIX THE TWITCH E!

I Wanna reach Diamond on my new account due to ban got me ...
Twitch without E isnt the samething

It only gets used when 5 stacked i want it to be used when it can kill the enemy.

**Comment by SephLeague** [comment]
It seems like an assembly related problem. The common only provides damage calculations, its up to the assemblies when to cast the E.

**Comment by xKurisu** [comment]
Its a bug with the core. Twitch E stacks always returns 1. :/

**Comment by mozartsharp** [comment]
Its not assemblie problem... i tried alot of twitch assemblies

**Comment by SephLeague** [comment]
I see, then it is a core issue. You have to wait for Joduskame to fix it.

**Comment by mozartsharp** [comment]
Okay so no diamond this season

**Comment by mozartsharp** [comment]
Im testing the fix now

**Comment by mozartsharp** [comment]
Tested, its weird but well works i hope

**Comment by mozartsharp** [comment]
Its using E when its 5 stacks z.z

**Comment by xKurisu** [comment]
This commit only fixed the damage his E returns so kill stealing/executing should be fixed. It's still up to the assembly when to cast E on X number of stacks. Twitch# is the only one that I know of that should cast E on 6 stacks.

**Comment by mozartsharp** [comment]
Okay do you got any idea why L# is making everyone getting low frames now

Earlier today i had 200 frames now the latest game i played i was 20 fps

**Comment by mozartsharp** [comment]
Please Revert the Twitch E fix as it makes you frame drop ALOT!!!

Test it yourself

**Comment by legacy3** [comment]
Well its a pretty heavy call but I doubt that it drops 180 frames ;!
